### ISSUE TITLE
Send amount $ preview

### ISSUE THREAD

**Issue by Nixxerr** [NixPlatform/Nix-GUI#103]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
 
When entering amount to send, it overlaps the equivalent $ preview

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Enter a large amount in the send field

# More information

- Operating system and version: Mac OS High Sierra 10.13.6
- Client version: V.1.0.0 GUI

**Comment by rbfront** [comment]
Fix pushed.

**Comment by mattt21** [comment]
Fixed, will be available in next release.
