### ISSUE TITLE
$ equivalent send amount remains after deletion of field

### ISSUE THREAD

**Issue by Nixxerr** [NixPlatform/Nix-GUI#104]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
  When entering an amount eg 12345, the $ preview amount updates, but when deleted, $ preview remains for first digit

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Enter a double digit amount or more to send 
2. Delete total amount clearing the field
3. The $ equivalent of the first digit will still preview. Should be ($0.00)

# More information

- Operating system and version: Mac )S High Sierra 10.13.6
- Client version: V.1.0.0 GUI

**Comment by rbfront** [comment]
Fix pushed.

**Comment by mattt21** [comment]
Fixed, will be available in next release.
