### ISSUE TITLE
<Enhancement> Hand pointer on transactions

### ISSUE THREAD

**Issue by Nixxerr** [NixPlatform/Nix-GUI#107]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

A hand pointer instead of regular cursor to change when hovering over transactions, to know its 'clickable'.

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by mattt21** [comment]
Add this over subviews you can click as well: Total ghostnode subview which takes user to ghostnode list. NIX price chart sub view which takes user to nix price chart page.

**Comment by Nixxerr** [comment]
It was for when clicking on an individual transaction itself in the transaction tab to view hash etc. Not from overview.

**Comment by mattt21** [comment]
Fixed. Will be included in the next release.
