### ISSUE TITLE
UI Wallet sync stuck on 97349

### ISSUE THREAD

**Issue by unbelievable-jeff** [NixPlatform/Nix-GUI#118]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
The UI wallet after not being opened for around 10 days will not sync to current block height and is stuck on 97349. I deleted Chainstate, Blocks, Peers, and Banlist, started the sync from scratch to no avail - stuck on same 97349 again. I came out of the UI once more, deleted only the Peers and Banlist, reopened but it still won't sync.
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

Won't sync on my machine

# More information

- Operating system and version:
Windows 7 x64, 
UI version 1.0.0

Debug should be available here: 
[debug.zip](https://github.com/NixPlatform/Nix-GUI/files/2615310/debug.zip)

**Comment by dacx** [comment]
Is this resolved with v1.0.1?

**Comment by mattt21** [comment]
The GUI uses nixd, nix-cli - it is not a gui issue, instead, it is a core issue. Report your log to the nix core repo. A temp fix is to delete chainstate and blocks in the nix appdata folder.
