### ISSUE TITLE
Cant paste address in 'new address' UI wallet Mac version

### ISSUE THREAD

**Issue by machinejarvis** [NixPlatform/Nix-GUI#92]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

If you copy (control C) a address you can not paste (control V) the address in beta UI wallet in new addresses. 

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. copy
2. paste

# More information

- Operating system and version: MacOS high Sierra 10.13.6 
- Client version:

**Comment by mattt21** [comment]
Fixed, will be available in next release.

**Comment by machinejarvis** [comment]
Nice
