### ISSUE TITLE
Staking Turns Off

### ISSUE THREAD

**Issue by H7USHKA** [NixPlatform/Nix-GUI#93]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

Staking button is switched off when activated then move to another tab (i.e. Overview, Ghost, etc.)
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Unlock wallet
2. Go to staking & Unlock for Staking
3. Click Overview
4. Navigate back to Staking

# More information

- Operating system and version: Windows 10 (Windows Server 2016 Datacenter)
- Client version: UI beta

**Comment by mattt21** [comment]
Fixed, will be available in next release.
