### ISSUE TITLE
UI abruptly closes after Password Encryption

### ISSUE THREAD

**Issue by H7USHKA** [NixPlatform/Nix-GUI#95]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
Mentioned this within the Discord but logging here. 

After you set your password, it just prompts a close which is typical after encryption. Maybe I missed it but didn't realize/see a notice about it closing. to be honest, thought is was a crash
Might be worth creating a prompt, "Nix Core will shut down now due to password/wallet encryption"

Jackieboy did mention the notification about closing is in the bottom right. IMO it should be more clear that the exe needs to close to encrypt. 
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Open Wallet
2. Encrypt Wallet
3. Promptly closes

# More information

- Operating system and version: Windows 10 (Windows Server 2016 Datacenter)
- Client version: UI Beta

**Comment by mattt21** [comment]
Fixed, will be available in next release.
