### ISSUE TITLE
In the staking tab --> when enabling the stake (Staking: ON) --> Transaction being staked --> There are no transactions showing in this area, but I am supposedly staking

### ISSUE THREAD

**Issue by s2nch** [NixPlatform/Nix-GUI#96]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by mattt21** [comment]
Use proper issue reporting(Not all details in the title).

**Comment by s2nch** [comment]
Describe bug/issue
No transactions showing in the Staking tab.

How to reproduce
1...Staking Tab in wallet.
2...Enable Staking.
3..."Transactions being staked" ---> No transactions while there is an amount being staked

..
..
More information
Operating system and version:
Client version:
