### ISSUE TITLE
For some reason the time of the last payout appears as: https://gyazo.com/c631e12d41857d406c9ae89963522dbd

### ISSUE THREAD

**Issue by s2nch** [NixPlatform/Nix-GUI#97]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by mattt21** [comment]
Use proper issue reporting(Not all details in the title).
